"""Trace + Event schemas.

Design notes:
- Every event carries `kind` (EventKind) so the client + backend can
  polymorphically dispatch on it without inheritance games.
- `Event` is the base with common fields; specialized shapes
  (RetrievalEvent, GenerationEvent, EmbeddingEvent) subclass it and add
  fields under `data` — the SDK is free to only fill what it has.
- `TraceIngestBatch` is the shape POSTed to `/v1/traces/batch`.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.common import EventKind, TraceStatus


# ---------------------------------------------------------------------------
# Chunk
# ---------------------------------------------------------------------------
class Chunk(BaseModel):
    """A single retrieved passage."""

    id: str = Field(..., description="Chunk identifier from the vector store or corpus.")
    content: str = Field(..., description="Raw text of the chunk (may be truncated by SDK).")
    score: float | None = Field(
        default=None, description="Similarity or rerank score assigned to this chunk."
    )
    rank: int | None = Field(
        default=None, description="1-based rank of this chunk within the retrieval result."
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Free-form metadata attached to the chunk (source, doc_id, page, etc.).",
    )

    model_config = ConfigDict(extra="allow")


# ---------------------------------------------------------------------------
# Base event
# ---------------------------------------------------------------------------
class Event(BaseModel):
    """One step in a RAG pipeline (embedding, retrieval, rerank, generation, custom)."""

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4, description="Unique event id, generated by SDK."
    )
    trace_id: uuid.UUID = Field(..., description="Trace this event belongs to.")
    parent_id: uuid.UUID | None = Field(
        default=None, description="Parent event id (for nested spans)."
    )
    kind: EventKind = Field(..., description="Event kind — enables polymorphic dispatch.")
    name: str = Field(
        ..., description="Human-readable label, e.g. 'openai.embeddings' or 'rerank.bge'."
    )
    start_time: datetime = Field(..., description="UTC start timestamp of the event.")
    end_time: datetime = Field(..., description="UTC end timestamp of the event.")
    duration_ms: float = Field(
        ..., description="end_time − start_time in milliseconds (SDK-computed).", ge=0
    )
    data: dict[str, Any] = Field(
        default_factory=dict,
        description="Kind-specific payload. See RetrievalEvent / GenerationEvent for the "
        "expected shape when kind ∈ {retrieval, generation, embedding}.",
    )
    error: str | None = Field(
        default=None, description="Error message if the step failed. None means success."
    )

    model_config = ConfigDict(extra="forbid")


# ---------------------------------------------------------------------------
# Specialized event shapes (client-side; backend stores them as Event + data).
# ---------------------------------------------------------------------------
class EmbeddingEvent(Event):
    """Embedding call. `data` is expected to include model + input + vector dim."""

    kind: Literal[EventKind.EMBEDDING] = Field(default=EventKind.EMBEDDING)


class RetrievalEvent(Event):
    """Retrieval / rerank step. `data` typically holds {'query': ..., 'chunks': [...]}."""

    kind: Literal[EventKind.RETRIEVAL] = Field(default=EventKind.RETRIEVAL)


class GenerationEvent(Event):
    """LLM call. `data` typically holds {'model': ..., 'prompt': ..., 'response': ..., 'tokens': {...}}."""

    kind: Literal[EventKind.GENERATION] = Field(default=EventKind.GENERATION)


# ---------------------------------------------------------------------------
# Trace
# ---------------------------------------------------------------------------
class Trace(BaseModel):
    """One end-to-end pipeline run: a query goes in, an answer comes out."""

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4, description="Trace id, generated client-side by SDK."
    )
    project_id: uuid.UUID = Field(
        ..., description="Project this trace belongs to (resolved from API key server-side)."
    )
    query: str = Field(..., description="The user-facing query that kicked off the pipeline.")
    answer: str | None = Field(
        default=None, description="Final LLM answer, if the pipeline reached generation."
    )
    start_time: datetime = Field(..., description="UTC start timestamp of the trace.")
    end_time: datetime = Field(..., description="UTC end timestamp of the trace.")
    duration_ms: float = Field(
        ..., description="Total trace duration in ms.", ge=0
    )
    status: TraceStatus = Field(..., description="Terminal status of the trace.")
    cost_usd: float | None = Field(
        default=None, description="Total cost of the trace in USD (SDK-computed).", ge=0
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Free-form tags: user_id, session_id, experiment tag, etc.",
    )

    model_config = ConfigDict(extra="allow")


class TraceCreate(BaseModel):
    """Ingest shape — a Trace plus its events."""

    trace: Trace = Field(..., description="Trace-level fields.")
    events: list[Event] = Field(
        default_factory=list,
        description="All events under this trace, in start_time order (SDK guarantees).",
    )


class TraceIngestBatch(BaseModel):
    """Body of POST /v1/traces/batch — a batch of trace-with-events objects."""

    items: list[TraceCreate] = Field(
        ...,
        description="One or more traces to ingest. SDK batches to reduce HTTP overhead.",
        min_length=1,
        max_length=500,
    )
